name: Learn Git Action CI
on:
  push:
    branches:
    - development
jobs:
  Development:
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
      - name: Install Yarn
        run: yarn
      - name: yarn build
        run: yarn build
     
