name: Learn Git Action CI
on:
  push:
    branches:
      - development
jobs:
  Development:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Install Yarn
        run: yarn
      - name: yarn build
        run: yarn build
      - name: Upload /build to S3
        run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET_NAME}}/development --recursive
        run: aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET_NAME}}/development --recursive
  Production:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/production' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Install Yarn
        run: yarn
      - name: yarn build
        run: yarn build
      - name: Upload /build to S3
        run: aws s3 rm s3://${{ secrets.AWS_S3_BUCKET_NAME}}/production --recursive
        run: aws s3 cp ./build s3://${{ secrets.AWS_S3_BUCKET_NAME}}/production --recursive
